# Generated by Django 4.2.2 on 2023-09-01 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial_api", "0002_remove_customuser_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phonenumber",
            field=models.CharField(default="081", max_length=20),
        ),
        migrations.CreateModel(
            name="UserHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Successful", "Successful"),
                            ("Pending", "Pending"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=11,
                    ),
                ),
                (
                    "Transaction",
                    models.CharField(
                        choices=[("Withdrawal", "Withdrawal"), ("Deposit", "Deposit")],
                        max_length=11,
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAccountModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Current_balance", models.FloatField(default=0.0)),
                ("Account_balance", models.FloatField(default=0.0)),
                ("Savings_balance", models.FloatField(default=0.0)),
                ("Investment", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
