# Generated by Django 4.2.2 on 2023-09-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_api", "0003_customuser_phonenumber_userhistory_useraccountmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phonenumber",
            field=models.CharField(max_length=20),
        ),
    ]
