# Generated by Django 4.2.2 on 2023-10-18 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial_api", "0005_userprofilemodel_alter_userhistory_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userhistory",
            name="Transaction",
            field=models.CharField(
                choices=[
                    ("Withdrawal", "Withdrawal"),
                    ("Deposit", "Deposit"),
                    ("Plan", "Plan"),
                ],
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="amount",
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.CreateModel(
            name="CryptoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bitcoin",
                    models.CharField(
                        default="this is the default crypto available ", max_length=70
                    ),
                ),
                (
                    "etherium",
                    models.CharField(
                        default="this is the default crypto available ", max_length=70
                    ),
                ),
                (
                    "litecoin",
                    models.CharField(
                        default="this is the default crypto available ", max_length=70
                    ),
                ),
                (
                    "usdt",
                    models.CharField(
                        default="this is the default crypto available ", max_length=70
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
