# Generated by Django 4.2.2 on 2023-10-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_api", "0008_userhistory_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhistory",
            name="disc",
            field=models.CharField(default="2023-12-10", max_length=100),
            preserve_default=False,
        ),
    ]
